module.exports =
{
  boards:
  [
    {
      "type":"board",
      "id":11,
      "level":0,
      "draft":0,
      "lastMod":1385464417000,
      "tiles":[
      {
        "x":0.17,
        "id":2,
        "type":"tile",
        "angle":-19,
        "y":0.66
      },
      {
        "x":0.47,
        "id":1,
        "type":"tile",
        "angle":-5,
        "y":0.38
      },
      {
        "x":0.83,
        "id":0,
        "type":"tile",
        "angle":198,
        "y":0.74
      }
    ],
    "paths":[
    {
      "nWords":6,
      "cw":1,
      "id":3,
      "type":"path",
      "maxCurve":0,
      "minCurve":0,
      "startTile":1,
      "endTile":0
    },
    {
      "nWords":3,
      "cw":1,
      "id":2,
      "type":"path",
      "maxCurve":0,
      "minCurve":0,
      "startTile":1,
      "endTile":0
    },
    {
      "nWords":3,
      "cw":0,
      "id":1,
      "type":"path",
      "maxCurve":0,
      "minCurve":0,
      "startTile":2,
      "endTile":1
    },
    {
      "nWords":6,
      "cw":0,
      "id":0,
      "type":"path",
      "maxCurve":0,
      "minCurve":0,
      "startTile":2,
      "endTile":1
    }
    ]
    },
    {
      "type":"board",
      "id":12,
      "level":0,
      "draft":0,
      "lastMod":1385459602000,
      "tiles":[
      {
        "x":0.12,
        "id":2,
        "type":"tile",
        "angle":-6,
        "y":0.41
      },
      {
        "x":0.47,
        "id":1,
        "type":"tile",
        "angle":174,
        "y":0.78
      },
      {
        "x":0.85,
        "id":0,
        "type":"tile",
        "angle":6,
        "y":0.47
      }
      ],
      "paths":[
      {
        "nWords":6,
        "cw":1,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      },
      {
        "nWords":3,
        "cw":1,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":0
      },
      {
        "nWords":4,
        "cw":0,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      }
      ]
    },
    {
      "lastMod":1385547676000,
      "draft":0,
      "level":0,
      "id":14,
      "type":"board",
      "tiles":[
      {
        "x":0.21,
        "id":2,
        "type":"tile",
        "angle":-14,
        "y":0.28
      },
      {
        "x":0.37,
        "id":1,
        "type":"tile",
        "angle":203,
        "y":0.78
      },
      {
        "x":0.8,
        "id":0,
        "type":"tile",
        "angle":17,
        "y":0.52
      }
      ],
      "paths":[
      {
        "nWords":5,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      },
      {
        "nWords":5,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      }
      ]
    },
    {
      "draft":0,
      "level":0,
      "id":16,
      "type":"board",
      "lastMod":1385547270000,
      "tiles":[
      {
        "x":0.14,
        "id":2,
        "type":"tile",
        "angle":-14,
        "y":0.25
      },
      {
        "x":0.88,
        "id":1,
        "type":"tile",
        "angle":-20,
        "y":0.33
      },
      {
        "x":0.47,
        "id":0,
        "type":"tile",
        "angle":188,
        "y":0.78
      }
      ],
      "paths":[
      {
        "nWords":6,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":3,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":5,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      }
      ]
    },
    {
      "draft":0,
      "level":1,
      "id":22,
      "type":"board",
      "lastMod":1385117172000,
      "tiles":[
      {
        "x":0.83,
        "id":2,
        "type":"tile",
        "angle":18,
        "y":0.4
      },
      {
        "x":0.49,
        "id":1,
        "type":"tile",
        "angle":173,
        "y":0.79
      },
      {
        "x":0.14,
        "id":0,
        "type":"tile",
        "angle":-21,
        "y":0.36
      }
      ],
      "paths":[
      {
        "nWords":5,
        "cw":1,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":4,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":0,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":0,
        "cw":0,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":2
      }
      ]
    },
    {
      "level":2,
      "draft":0,
      "lastMod":1385476394000,
      "type":"board",
      "id":23,
      "tiles":[
      {
        "x":0.59,
        "id":3,
        "type":"tile",
        "angle":13,
        "y":0.32
      },
      {
        "x":0.86,
        "id":2,
        "type":"tile",
        "angle":153,
        "y":0.71
      },
      {
        "x":0.19,
        "id":1,
        "type":"tile",
        "angle":198,
        "y":0.74
      },
      {
        "x":0.17,
        "id":0,
        "type":"tile",
        "angle":-18,
        "y":0.24
      }
      ],
      "paths":[
      {
        "nWords":4,
        "cw":0,
        "id":5,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":3
      },
      {
        "nWords":4,
        "cw":0,
        "id":4,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":3
      },
      {
        "nWords":3,
        "cw":1,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":3
      },
      {
        "nWords":5,
        "cw":0,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":2
      },
      {
        "nWords":0,
        "cw":1,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":3,
        "endTile":2
      },
      {
        "nWords":3,
        "cw":0,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      }
      ]
    },
    {
      "level":1,
      "draft":0,
      "lastMod":1385476526000,
      "type":"board",
      "id":20,
      "tiles":[
      {
        "x":0.16,
        "id":3,
        "type":"tile",
        "angle":-6,
        "y":0.2
      },
      {
        "x":0.57,
        "id":2,
        "type":"tile",
        "angle":192,
        "y":0.77
      },
      {
        "x":0.85,
        "id":1,
        "type":"tile",
        "angle":16,
        "y":0.49
      },
      {
        "x":0.15,
        "id":0,
        "type":"tile",
        "angle":205,
        "y":0.82
      }
      ],
      "paths":[
      {
        "nWords":4,
        "cw":0,
        "id":5,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      },
      {
        "nWords":5,
        "cw":1,
        "id":4,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":3,
        "endTile":1
      },
      {
        "nWords":4,
        "cw":1,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":3,
        "endTile":2
      },
      {
        "nWords":3,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":3
      },
      {
        "nWords":3,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":3
      },
      {
        "nWords":3,
        "cw":0,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      }
      ]
    },
    {
      "draft":0,
      "level":0,
      "id":2,
      "type":"board",
      "lastMod":1385115236000,
      "tiles":[
      {
        "x":0.48,
        "id":2,
        "type":"tile",
        "angle":182,
        "y":0.8
      },
      {
        "x":0.81,
        "id":1,
        "type":"tile",
        "angle":11,
        "y":0.37
      },
      {
        "x":0.13,
        "id":0,
        "type":"tile",
        "angle":-19,
        "y":0.38
      }
      ],
      "paths":[
      {
        "nWords":4,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      },
      {
        "nWords":4,
        "cw":0,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":3,
        "cw":1,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":5,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      }
      ]
    },
    {
      "draft":0,
      "level":0,
      "id":3,
      "type":"board",
      "lastMod":1385547604000,
      "tiles":[
      {
        "x":0.88,
        "id":2,
        "type":"tile",
        "angle":200,
        "y":0.66
      },
      {
        "x":0.14,
        "id":1,
        "type":"tile",
        "angle":171,
        "y":0.76
      },
      {
        "x":0.48,
        "id":0,
        "type":"tile",
        "angle":-3,
        "y":0.36
      }
      ],
      "paths":[
      {
        "nWords":3,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":0
      },
      {
        "nWords":5,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":5,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      }
      ]
    },
    {
      "draft":0,
      "level":1,
      "id":24,
      "type":"board",
      "lastMod":1385477273000,
      "tiles":[
      {
        "x":0.5,
        "id":2,
        "type":"tile",
        "angle":-1,
        "y":0.35
      },
      {
        "x":0.88,
        "id":1,
        "type":"tile",
        "angle":159,
        "y":0.71
      },
      {
        "x":0.12,
        "id":0,
        "type":"tile",
        "angle":205,
        "y":0.73
      }
      ],
      "paths":[
      {
        "nWords":3,
        "cw":0,
        "id":5,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      },
      {
        "nWords":6,
        "cw":0,
        "id":4,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":3,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":3,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":0,
        "cw":1,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      },
      {
        "nWords":6,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      }
      ]
    },
    {
      "representedWord":"around",
      "owner":"ali",
      "isRelated":false,
      "class":"preposition",
      "x":0.5700000000000001,
      "y":-0.006594772117678076,
      "angle":-0.33816856564953923,
      "collection":"basic",
      "id":6,
      "type":"magnetPlayer",
      "tiles":[
      
      ],
      "paths":[
      
      ]
    },
    {
      "type":"board",
      "level":0,
      "draft":0,
      "tiles":[
      {
        "representedImage":"old_woman",
        "id":0,
        "type":"tile",
        "x":0.13,
        "angle":-19,
        "representedInstruction":0,
        "y":0.38
      },
      {
        "representedInstruction":1,
        "representedImage":"fire",
        "id":1,
        "type":"tile",
        "x":0.81,
        "angle":11,
        "y":0.37
      },
      {
        "representedImage":"clock_in_sand",
        "id":2,
        "type":"tile",
        "x":0.48,
        "angle":182,
        "representedInstruction":6,
        "y":0.8
      }
      ],
      "paths":[
      {
        "startTile":0,
        "cw":1,
        "id":3,
        "type":"path",
        "nWords":5,
        "endTile":1
      },
      {
        "startTile":0,
        "cw":1,
        "id":2,
        "type":"path",
        "nWords":3,
        "endTile":2
      },
      {
        "startTile":0,
        "cw":0,
        "id":1,
        "type":"path",
        "nWords":4,
        "endTile":2
      },
      {
        "startTile":2,
        "cw":0,
        "id":0,
        "type":"path",
        "nWords":4,
        "endTile":1
      }
      ]
    },
    {
      "representedImage":"clock_in_sand",
      "id":2,
      "type":"tile",
      "x":0.48,
      "angle":182,
      "representedInstruction":6,
      "y":0.8,
      "tiles":[
      
      ],
      "paths":[
      
      ]
    },
    {
      "lastMod":1385654618000,
      "draft":0,
      "level":2,
      "id":27,
      "type":"board",
      "tiles":[
      {
        "x":0.14,
        "id":3,
        "type":"tile",
        "angle":-19,
        "y":0.23
      },
      {
        "x":0.28,
        "id":2,
        "type":"tile",
        "angle":207,
        "y":0.8
      },
      {
        "x":0.81,
        "id":1,
        "type":"tile",
        "angle":207,
        "y":0.21
      },
      {
        "x":0.82,
        "id":0,
        "type":"tile",
        "angle":163,
        "y":0.79
      }
      ],
      "paths":[
      {
        "nWords":3,
        "cw":1,
        "id":5,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":1,
        "id":4,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      },
      {
        "nWords":0,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":3,
        "endTile":2
      },
      {
        "nWords":5,
        "cw":1,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      },
      {
        "nWords":3,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":0
      },
      {
        "nWords":6,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":2,
        "endTile":1
      }
      ]
    },
    {
      "draft":0,
      "level":1,
      "id":28,
      "type":"board",
      "lastMod":1385477223000,
      "tiles":[
      {
        "x":0.82,
        "id":2,
        "type":"tile",
        "angle":18,
        "y":0.25
      },
      {
        "x":0.44,
        "id":1,
        "type":"tile",
        "angle":8,
        "y":0.8
      },
      {
        "x":0.15,
        "id":0,
        "type":"tile",
        "angle":-16,
        "y":0.18
      }
      ],
      "paths":[
      {
        "nWords":3,
        "cw":0,
        "id":5,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":6,
        "cw":0,
        "id":4,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":2
      },
      {
        "nWords":3,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":1,
        "endTile":2
      },
      {
        "nWords":6,
        "cw":0,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":5,
        "cw":0,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      },
      {
        "nWords":3,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":2
      }
      ]
    },
    {
      "draft":0,
      "level":0,
      "id":29,
      "type":"board",
      "lastMod":1385477399000,
      "tiles":[
      {
        "x":0.76,
        "id":1,
        "type":"tile",
        "angle":23,
        "y":0.48
      },
      {
        "x":0.19,
        "id":0,
        "type":"tile",
        "angle":-30,
        "y":0.48
      }
      ],
      "paths":[
      {
        "nWords":3,
        "cw":0,
        "id":3,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":6,
        "cw":0,
        "id":2,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":5,
        "cw":1,
        "id":1,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      },
      {
        "nWords":3,
        "cw":1,
        "id":0,
        "type":"path",
        "maxCurve":0,
        "minCurve":0,
        "startTile":0,
        "endTile":1
      }
      ]
    }
  ]
}